//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib_LocationVoiture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.reservations = new HashSet<reservation>();
            this.factures = new HashSet<facture>();
        }
    
        public int clientID { get; set; }
        public string password { get; set; }
        public string nom { get; set; }
        public Nullable<System.DateTime> date_enregistrement { get; set; }
        public string telephone { get; set; }
        public string adresse_client { get; set; }
        public Nullable<long> num_carte_credit { get; set; }
        public string permis_conduire_num { get; set; }
        public string assurance { get; set; }
        public string courriel { get; set; }
        public string prenom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservation> reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facture> factures { get; set; }
    }
}
