//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib_LocationVoiture.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class locationVoitures : DbContext
    {
        public locationVoitures()
            : base("name=locationVoitures")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administrateur> administrateurs { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<constats_dommages> constats_dommages { get; set; }
        public virtual DbSet<employe> employes { get; set; }
        public virtual DbSet<fabriquant> fabriquants { get; set; }
        public virtual DbSet<facture> factures { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<modele> modeles { get; set; }
        public virtual DbSet<reservation> reservations { get; set; }
        public virtual DbSet<succursale> succursales { get; set; }
        public virtual DbSet<type> types { get; set; }
        public virtual DbSet<vehicule> vehicules { get; set; }
    }
}
